on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create a release

jobs:
  build:
    name: Create a release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make
        uses: ./.github/actions/build-sqljs
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - run: cd dist && zip sqljs-wasm.zip sql-wasm.{js,wasm}
      - name: Upload Release Asset (wasm)
        uses: lovasoa/upload-release-asset@851d9cc59fe8113912edffbd8fddaa09470a5ac0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/sqljs-wasm.zip
          asset_name: sqljs-wasm.zip
          asset_label: wasm version, best runtime performance, smaller assets, requires configuration
          asset_content_type: application/zip
